### PR TITLE
Fix empty jade config

### PR DESCRIPTION
**Pull request by axtloss**
Fixes the bug where the generated jade config written to /tmp/jade.json would be empty.

### CODE REVIEW

**Review by mchalunderscore — CHANGES_REQUESTED** [review]
Merge commits like this really pollute and mess with the Git history, why was this done?

**Comment by axtloss** [comment]
there were merge conflicts which GitHub said I could fix in the web editor, so I did that.
I didn't know it would pollute stuff.

**Comment by mchalunderscore** [comment]
In that case this is a case of GitHub naming a commit something else than it actually is. This is fine

**Comment by mchalunderscore** [comment]
GitHub mobile is being stupid. I'll mark this as approved once I get home

**Review by mchalunderscore — APPROVED** [review]

**Pull request merged**
