### PR TITLE
change binary file to jade-gui

### PR DESCRIPTION
**Pull request by axtloss**

### CODE REVIEW

**Comment by axtloss** [comment]
how do i remove that extra commit that's there for some reason

**Comment by fries1234** [comment]
the fix logging one?

**Comment by axtloss** [comment]
yes

**Comment by mchalunderscore** [comment]
`git rebase -i HEAD~5` on the branch, `drop` it then `git push --force`

**Comment by fries1234** [comment]
aw i was gonna say to do something with interactive rebase but you seem to know git alot more then me

**Comment by axtloss** [comment]
is this right?

**Comment by mchalunderscore** [comment]
This looks good!

**Review by mchalunderscore — APPROVED** [review]

**Comment by Antiz96** [comment]
Wait!

**Comment by fries1234** [comment]
yeah that looks good

**Comment by axtloss** [comment]
> Wait!

what's the issue?

**Comment by Antiz96** [comment]
> > Wait!
> 
> what's the issue?

Sorry for the brut answer I had to be quick before you merge x)

Since the binary is renamed to `jade-gui`, shouldn't this PR change the `Exec` line of the [.desktop file](https://github.com/crystal-linux/jade-gui/blob/main/data/al.getcryst.jadegui.desktop.in) accordingly?

EDIT: Forget it, I'm blind. My bad.

**Comment by axtloss** [comment]
I did that already https://github.com/crystal-linux/jade-gui/pull/66/files#diff-4d2098dcbd8be739e34b41c473acaa77b6ab96ad7edeee50f41b13257bcbadbd

**Review by fries1234 — APPROVED** [review]

**Comment by Antiz96** [comment]
> I did that already https://github.com/crystal-linux/jade-gui/pull/66/files#diff-4d2098dcbd8be739e34b41c473acaa77b6ab96ad7edeee50f41b13257bcbadbd

Yup, I edited my comment. I'm blind, my bad.... Looks good.

**Pull request merged**
